<?php
/**
 * Final save coverage bridge for the owner visual editor.
 *
 * The historic editor grew several specialist runtimes. This bridge makes the
 * visible Save actions persist every dirty runtime, and attaches one common
 * history-group id to the requests generated by one user Save gesture.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

add_action( 'wp_footer', static function () {
    if ( ! is_user_logged_in() || ! current_user_can( 'edit_pages' ) ) { return; }
    ?>
    <script id="kp-unified-save-coverage">
    (()=>{
      'use strict';
      const ACTION_RE=/^kp_(owner_(design|sizes|menu_x|nav)_save|fe_v2_save|touch_(free_layout|gesture)_save|image_position_save|canva_image_save|frontend_card_(image|button)_save|fe_v2_record_save|ai_.*_save)$/;
      let saveGroup='',groupTimer=0;
      const makeGroup=()=>`save-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`;
      function beginGroup(){clearTimeout(groupTimer);saveGroup=makeGroup();groupTimer=setTimeout(()=>{saveGroup=''},12000);return saveGroup}
      function actionFromBody(body){
        try{
          if(body instanceof FormData)return String(body.get('action')||'');
          if(body instanceof URLSearchParams)return String(body.get('action')||'');
          if(typeof body==='string')return String(new URLSearchParams(body).get('action')||'');
        }catch(_){}return '';
      }
      const inheritedFetch=window.fetch.bind(window);
      window.fetch=(input,init={})=>{
        try{
          const body=init?.body,action=actionFromBody(body);
          if(saveGroup&&ACTION_RE.test(action)){
            if(body instanceof FormData&&!body.has('kp_history_group'))body.append('kp_history_group',saveGroup);
            else if(body instanceof URLSearchParams&&!body.has('kp_history_group'))body.append('kp_history_group',saveGroup);
            else if(typeof body==='string'){
              const p=new URLSearchParams(body);if(!p.has('kp_history_group'))p.set('kp_history_group',saveGroup);init={...init,body:p.toString()};
            }
          }
        }catch(_){}
        return inheritedFetch(input,init);
      };

      function installRegistryCoverage(){
        const registry=window.KPOwnerSaveRegistry;
        if(!registry||registry.__kpUnifiedCoverage)return false;
        const baseFlush=registry.flushAll?.bind(registry),baseDirty=registry.isDirty?.bind(registry);
        registry.flushAll=async()=>{
          const result=baseFlush?await baseFlush():{success:true};
          if(window.KPCanvaLayoutRuntime?.flush)await window.KPCanvaLayoutRuntime.flush();
          if(window.KPCanvaImageRuntime?.flush)await window.KPCanvaImageRuntime.flush();
          if(window.KPAIEditorRuntime?.flush)await window.KPAIEditorRuntime.flush();
          return result||{success:true};
        };
        registry.isDirty=()=>!!baseDirty?.()||!!window.KPCanvaLayoutRuntime?.isDirty?.()||!!window.KPCanvaImageRuntime?.isDirty?.()||!!window.KPAIEditorRuntime?.isDirty?.();
        registry.__kpUnifiedCoverage=true;
        return true;
      }
      installRegistryCoverage();setInterval(installRegistryCoverage,250);

      document.addEventListener('click',e=>{
        const t=e.target instanceof Element?e.target:null;if(!t)return;
        if(t.closest('.kp-fe2-save,.kp-oa-design-save,.kp-oa-size-save,.kp-fe2-record-main-save,.kp-fe-card-save'))beginGroup();
      },true);

      window.KPUnifiedSaveCoverage={beginGroup,currentGroup:()=>saveGroup,refresh:installRegistryCoverage};
    })();
    </script>
    <?php
}, 1900 );
