const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const main=$('main');const defaults=main.innerHTML;const STORAGE='kp-webapp-content-v2',DRAFT='kp-webapp-draft-v1';let undoStack=[],redoStack=[],editing=false,selectedSection=null,dirty=false,draftTimer=null,lastSnapshot='',bootSnapshot='',bootHadSaved=false;
const CLOUD_ENDPOINT='./api/editor-state.php';
const editable=()=>$$('main h1,main h2,main h3,main .lead,main section p:not(.eyebrow):not(.muted)');const images=()=>$$('main img');
function capture(){const copy=main.cloneNode(true);copy.querySelectorAll('.section-selected').forEach(e=>e.classList.remove('section-selected'));copy.querySelectorAll('.section-editable').forEach(e=>e.classList.remove('section-editable'));copy.querySelectorAll('.image-editable').forEach(e=>{e.classList.remove('image-editable');e.removeAttribute('title')});copy.querySelectorAll('[data-editor-wired],[data-image-wired],[data-section-wired]').forEach(e=>{e.removeAttribute('data-editor-wired');e.removeAttribute('data-image-wired');e.removeAttribute('data-section-wired')});copy.querySelectorAll('[contenteditable]').forEach(e=>e.setAttribute('contenteditable','false'));return copy.innerHTML}function restore(html){main.innerHTML=html;selectedSection=null;wireEditable();wireImages();wireSections();if(editing)setEditable(true)}
function setStatus(text){const s=$('#status');if(s)s.textContent=text}
function saveDraft(){if(!dirty)return;try{localStorage.setItem(DRAFT,JSON.stringify({html:capture(),savedAt:new Date().toISOString()}))}catch{} }
function clearDraft(){try{localStorage.removeItem(DRAFT)}catch{} }
function markDirty(message='Nicht gespeichert'){dirty=true;setStatus(message);clearTimeout(draftTimer);draftTimer=setTimeout(saveDraft,500);updateEditor()}
function markSaved(message){dirty=false;clearTimeout(draftTimer);clearDraft();lastSnapshot=capture();setStatus(message);updateEditor()}
function pushUndo(state=capture()){if(undoStack.at(-1)!==state)undoStack.push(state);if(undoStack.length>50)undoStack.shift();redoStack=[];updateEditor()}
function setEditable(on){editing=on;wireEditable();wireImages();wireSections();editable().forEach(e=>{e.contentEditable=on?'true':'false';e.spellcheck=true});images().forEach(img=>{img.classList.toggle('image-editable',on);img.title=on?'Tippen, um Bild zu ersetzen':''});$$('main>section').forEach(s=>s.classList.toggle('section-editable',on));if(!on)selectSection(null);$('#editor').hidden=!on;$('#edit').hidden=on;document.body.classList.toggle('editing',on);updateEditor()}
function wireEditable(){editable().forEach(e=>{if(e.dataset.editorWired)return;e.dataset.editorWired='1';let before='';e.addEventListener('focus',()=>{if(!editing)return;selectSection(e.closest('section'));before=capture()});e.addEventListener('input',()=>{if(!editing)return;if(before){pushUndo(before);before=''}markDirty()})})}
function wireImages(){images().forEach(img=>{if(img.dataset.imageWired)return;img.dataset.imageWired='1';img.addEventListener('click',e=>{if(!editing)return;e.preventDefault();e.stopPropagation();selectSection(img.closest('section'));replaceImage(img)})})}
function wireSections(){$$('main>section').forEach(s=>{if(s.dataset.sectionWired)return;s.dataset.sectionWired='1';s.addEventListener('click',e=>{if(editing&&!e.target.closest('a,button,summary,img'))selectSection(s)})})}
function selectSection(s){if(selectedSection)selectedSection.classList.remove('section-selected');selectedSection=s;if(s)s.classList.add('section-selected');updateEditor()}
function addSection(){pushUndo();const section=document.createElement('section');const dark=$$('main>section').length%2===1;section.className=dark?'dark':'';section.innerHTML='<div class="wrap"><p class="eyebrow">Neuer Abschnitt</p><h2>Neue Überschrift</h2><p>Hier können Sie Ihren neuen Text direkt bearbeiten.</p></div>';const anchor=selectedSection;if(anchor)anchor.after(section);else main.append(section);wireEditable();wireSections();setEditable(true);selectSection(section);markDirty('Neuer Abschnitt erstellt – noch speichern');section.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>section.querySelector('h2')?.focus(),350)}
function toggleSectionStyle(){if(!selectedSection)return;pushUndo();selectedSection.classList.toggle('dark');markDirty(selectedSection.classList.contains('dark')?'Dunkler Hintergrund gewählt – noch speichern':'Heller Hintergrund gewählt – noch speichern');updateEditor()}
function moveSection(dir){if(!selectedSection)return;const sibling=dir<0?selectedSection.previousElementSibling:selectedSection.nextElementSibling;if(!sibling)return;pushUndo();if(dir<0)main.insertBefore(selectedSection,sibling);else main.insertBefore(sibling,selectedSection);markDirty('Abschnitt verschoben – noch speichern');selectedSection.scrollIntoView({behavior:'smooth',block:'center'});updateEditor()}
function duplicateSection(){if(!selectedSection)return;pushUndo();const copy=selectedSection.cloneNode(true);copy.removeAttribute('id');copy.querySelectorAll('[id]').forEach(e=>e.removeAttribute('id'));copy.querySelectorAll('[data-editor-wired],[data-image-wired],[data-section-wired]').forEach(e=>{delete e.dataset.editorWired;delete e.dataset.imageWired;delete e.dataset.sectionWired});copy.classList.remove('section-selected');selectedSection.after(copy);wireEditable();wireImages();wireSections();selectSection(copy);markDirty('Abschnitt dupliziert – noch speichern');copy.scrollIntoView({behavior:'smooth',block:'center'})}
function toggleSection(){if(!selectedSection)return;pushUndo();const hidden=selectedSection.dataset.ownerHidden==='1';if(hidden){delete selectedSection.dataset.ownerHidden;selectedSection.classList.remove('owner-hidden')}else{selectedSection.dataset.ownerHidden='1';selectedSection.classList.add('owner-hidden')}markDirty(hidden?'Abschnitt wieder eingeblendet – noch speichern':'Abschnitt ausgeblendet – noch speichern');updateEditor()}
function deleteSection(){if(!selectedSection||$$('main>section').length<=1)return;const section=selectedSection;const label=(section.querySelector('h1,h2,h3')?.textContent||'diesen Abschnitt').trim();if(!confirm(`„${label}“ wirklich löschen?\n\nDu kannst die Löschung danach mit „Rückgängig“ zurückholen.`))return;pushUndo();const next=section.nextElementSibling||section.previousElementSibling;section.remove();selectedSection=null;if(next&&next.matches('section'))selectSection(next);markDirty('Abschnitt gelöscht – mit Rückgängig wiederherstellbar')}
function replaceImage(img){const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=()=>{const f=input.files&&input.files[0];if(!f)return;if(f.size>5*1024*1024){setStatus('Bild ist größer als 5 MB');return}pushUndo();const reader=new FileReader();reader.onload=()=>{img.src=reader.result;img.removeAttribute('srcset');img.loading='lazy';markDirty('Bild ersetzt – noch speichern')};reader.readAsDataURL(f)};input.click()}
function updateEditor(){const u=$('#undo'),r=$('#redo'),style=$('#sectionStyle'),up=$('#moveUp'),down=$('#moveDown'),dup=$('#duplicateSection'),toggle=$('#toggleSection'),del=$('#deleteSection'),save=$('#cloudSave');if(u)u.disabled=!undoStack.length;if(r)r.disabled=!redoStack.length;if(style){style.disabled=!selectedSection;style.textContent=selectedSection&&selectedSection.classList.contains('dark')?'☀ Hell':'◐ Dunkel'}if(up)up.disabled=!selectedSection||!selectedSection.previousElementSibling;if(down)down.disabled=!selectedSection||!selectedSection.nextElementSibling;if(dup)dup.disabled=!selectedSection;if(toggle){toggle.disabled=!selectedSection;toggle.textContent=selectedSection&&selectedSection.dataset.ownerHidden==='1'?'◉ Einblenden':'◉ Ausblenden'}if(del)del.disabled=!selectedSection||$$('main>section').length<=1;if(save)save.classList.toggle('unsaved',dirty)}
async function cloudRequest(method='GET',body){const r=await fetch(CLOUD_ENDPOINT,{method,credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});if(!r.ok){let msg='';try{msg=(await r.json()).error||''}catch{}throw Error(msg||`Server ${r.status}`)}return r.json()}
async function cloudLoad({silent=false}={}){try{const state=await cloudRequest();if(state.exists===false||!state.html){if(!silent)setStatus('Noch kein Cloud-Stand vorhanden');return false}pushUndo();restore(state.html);localStorage.setItem(STORAGE,capture());dirty=false;clearDraft();lastSnapshot=capture();setStatus(`Cloud-Stand geladen ✓${state.savedAt?' · '+new Date(state.savedAt).toLocaleString('de-DE'):''}`);updateEditor();return true}catch(e){if(!silent)setStatus('Cloud-Laden fehlgeschlagen: '+e.message);return false}}
async function cloudSave(){setStatus('Speichere in Cloud …');try{const payload={version:1,savedAt:new Date().toISOString(),html:capture()};await cloudRequest('PUT',payload);localStorage.setItem(STORAGE,payload.html);markSaved('Dauerhaft auf dem Webspace gespeichert ✓')}catch(e){dirty=true;saveDraft();setStatus('Cloud-Speichern fehlgeschlagen: '+e.message);updateEditor()}}
function recoverDraft(){try{const raw=localStorage.getItem(DRAFT);if(!raw)return false;const draft=JSON.parse(raw);if(!draft.html||draft.html===capture())return false;restore(draft.html);dirty=true;lastSnapshot='';setStatus(`Ungesicherten Entwurf wiederhergestellt${draft.savedAt?' · '+new Date(draft.savedAt).toLocaleString('de-DE'):''}`);updateEditor();return true}catch{return false}}
$('#edit').onclick=()=>{setEditable(true);setStatus(dirty?'Ungesicherte Änderungen':'Text, Bild oder Abschnitt antippen')};$('#close').onclick=()=>{saveDraft();setEditable(false)};
$('#save').onclick=()=>{try{localStorage.setItem(STORAGE,capture());markSaved('Auf diesem Gerät gespeichert ✓')}catch{setStatus('Speicher voll – kleineres Bild verwenden')}};if($('#cloudSave'))$('#cloudSave').onclick=cloudSave;if($('#cloudLoad'))$('#cloudLoad').onclick=()=>cloudLoad();if($('#cloudLogout'))$('#cloudLogout').onclick=()=>setStatus('Webspace-Speicher ist aktiv');
$('#undo').onclick=()=>{if(!undoStack.length)return;redoStack.push(capture());restore(undoStack.pop());markDirty('Änderung rückgängig – noch speichern')};$('#redo').onclick=()=>{if(!redoStack.length)return;undoStack.push(capture());restore(redoStack.pop());markDirty('Änderung wiederholt – noch speichern')};if($('#addSection'))$('#addSection').onclick=addSection;if($('#sectionStyle'))$('#sectionStyle').onclick=toggleSectionStyle;$('#moveUp').onclick=()=>moveSection(-1);$('#moveDown').onclick=()=>moveSection(1);if($('#duplicateSection'))$('#duplicateSection').onclick=duplicateSection;if($('#toggleSection'))$('#toggleSection').onclick=toggleSection;if($('#deleteSection'))$('#deleteSection').onclick=deleteSection;$('#reset').onclick=()=>{pushUndo();restore(defaults);markDirty('Standardwerte geladen – noch speichern')};
$('#menu').onclick=()=>$('#nav').classList.toggle('open');$('#nav').onclick=()=>$('#nav').classList.remove('open');const saved=localStorage.getItem(STORAGE)||localStorage.getItem('kp-webapp-content');if(saved){restore(saved);bootHadSaved=true}lastSnapshot=capture();recoverDraft();bootSnapshot=capture();if(dirty)bootHadSaved=true;wireEditable();wireImages();wireSections();
window.addEventListener('pagehide',saveDraft);window.addEventListener('beforeunload',e=>{saveDraft();if(dirty){e.preventDefault();e.returnValue=''}});
const dataBase='data/';const assetBase='assets/';const fallbackShows=[{title:'Zum Glück gibt’s FREUNDE',summary:'Drei Freunde aus Mullewapp zeigen, wie man gemeinsam Höhen und Tiefen meistert.',age:'bis 6 Jahre',duration:'20–40 Minuten'},{title:'Nulli und Priesemut',summary:'Zwei Geschichten über Angst, Freundschaft, Mobbing und Zusammenhalt.',age:'ab 3 Jahren',duration:'ca. 45 Minuten'}];function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function file(v=''){return encodeURIComponent(String(v)).replace(/%2F/g,'/')}
function showCards(items){const el=$('#shows');if(!el)return;el.innerHTML=items.map(x=>{const image=x.card_image||x.bundled_image||x.info_image||'';return `<article class="show-card">${image?`<img class="card-image" src="${assetBase}legacy-repertoire/${file(image)}" alt="${esc(x.title)}" loading="lazy">`:''}<div class="card-body"><p class="eyebrow">${esc(x.category||'Repertoire')}</p><h3>${esc(x.title)}</h3><p>${esc(x.summary||x.description||'')}</p><p class="muted">${esc([x.age,x.duration].filter(Boolean).join(' · '))}</p><details><summary>Stückdetails</summary>${x.players?`<p><b>Spiel:</b> ${esc(x.players)}</p>`:''}${x.play_style?`<p><b>Spielart:</b> ${esc(x.play_style)}</p>`:''}${x.premiere?`<p><b>Premiere:</b> ${esc(x.premiere)}</p>`:''}${x.technical?`<p><b>Technik:</b> ${esc(x.technical)}</p>`:''}</details><a class="ghost" href="#buchen">Dieses Stück anfragen</a></div></article>`}).join('');wireEditable();wireImages()}
function eventCards(items){const el=$('#events');if(!el)return;const today=new Date();today.setHours(0,0,0,0);let rows=items.map(x=>{const raw=x.date||x.start||x.datum||x.start_date||'';return {...x,_date:raw?new Date(raw):null}}).filter(x=>!x._date||isNaN(x._date)||x._date>=today).slice(0,6);el.innerHTML=(rows.length?rows:[{title:'Weitere Termine folgen'}]).map(x=>`<article><p class="eyebrow">${x._date&&!isNaN(x._date)?x._date.toLocaleDateString('de-DE'):'Termin'}</p><h3>${esc(x.title||x.stueck||x.name||'Vorstellung')}</h3><p>${esc(x.location||x.ort||x.description||x.text||'')}</p></article>`).join('');wireEditable()}
function ensembleCards(items){const el=$('#ensemble-cards');if(!el)return;const featured=items.filter(x=>x.featured);el.innerHTML=featured.map(x=>{const image=x.bundled_image||x.image||'';return `<article class="person">${image?`<img class="person-image" src="${assetBase}legacy-ensemble/${file(image)}" alt="${esc(x.title)}" loading="lazy">`:''}<div class="card-body"><p class="eyebrow">${esc(x.role||'Ensemble')}</p><h3>${esc(x.title)}</h3>${x.born?`<p class="muted">${esc(x.born)}</p>`:''}<p>${esc(x.short||'')}</p><details><summary>Mehr über ${esc((x.title||'').split(' ')[0])}</summary><p>${esc(x.bio||'')}</p></details></div></article>`}).join('');wireEditable();wireImages()}
function referenceCards(items){const el=$('#reference-cards');if(!el)return;el.innerHTML=items.map(x=>{const image=x.bundled_image||'';return `<a class="reference" href="${esc(x.url||'#')}" target="_blank" rel="noopener">${image?`<img src="${assetBase}legacy-referenzen/${file(image)}" alt="${esc(x.title)}" loading="lazy">`:''}<strong>${esc(x.title)}</strong><span>${esc(x.domain||'')}</span></a>`}).join('');wireImages()}
async function json(path){const r=await fetch(dataBase+path,{cache:'no-store'});if(!r.ok)throw Error('data unavailable');return r.json()}(async()=>{if(!bootHadSaved){try{showCards(await json('repertoire.json'))}catch{showCards(fallbackShows)}try{eventCards(await json('termine.json'))}catch{eventCards([])}try{ensembleCards(await json('ensemble.json'))}catch{}try{referenceCards(await json('referenzen.json'))}catch{}}else{restore(bootSnapshot)}wireSections();if(editing)setEditable(true)})();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
