(()=>{
  let selectedCard=null;
  const cardSelector='article,.person,.show-card';
  function setContext(mode,label=''){
    const cardTools=document.querySelector('#cardTools'),sectionTools=document.querySelector('#sectionTools'),context=document.querySelector('#editorContext');
    if(cardTools)cardTools.hidden=mode!=='card';if(sectionTools)sectionTools.hidden=mode==='card';
    if(context)context.textContent=mode==='card'?`Karte${label?': '+label:''}`:mode==='section'?'Abschnitt bearbeiten':'Seite bearbeiten';
  }
  function clearCard(){if(selectedCard)selectedCard.classList.remove('card-selected');selectedCard=null;setContext(selectedSection?'section':'page');updateCardControls()}
  function selectCard(card){if(selectedCard)selectedCard.classList.remove('card-selected');selectedCard=card||null;if(selectedCard){selectedCard.classList.add('card-selected');selectSection(selectedCard.closest('section'));const label=(selectedCard.querySelector('h3,h2,strong')?.textContent||'').trim();setContext('card',label)}else setContext(selectedSection?'section':'page');updateCardControls()}
  function updateCardControls(){
    const add=document.querySelector('#addCard'),dup=document.querySelector('#duplicateCard'),del=document.querySelector('#deleteCard'),image=document.querySelector('#cardImage'),left=document.querySelector('#cardLeft'),right=document.querySelector('#cardRight');
    const container=selectedSection?.querySelector('.cards');
    if(add)add.disabled=!selectedSection||!container;
    if(dup)dup.disabled=!selectedCard;if(del)del.disabled=!selectedCard;if(image){image.disabled=!selectedCard;image.textContent=selectedCard?.querySelector('img')?'▣ Bild ändern':'▣ Bild hinzufügen'}
    if(left)left.disabled=!selectedCard||!selectedCard.previousElementSibling;if(right)right.disabled=!selectedCard||!selectedCard.nextElementSibling;
  }
  function cleanClone(card){const copy=card.cloneNode(true);copy.classList.remove('card-selected');copy.querySelectorAll('[id]').forEach(el=>el.removeAttribute('id'));copy.querySelectorAll('[data-editor-wired],[data-image-wired],[data-section-wired],[data-card-wired]').forEach(el=>{el.removeAttribute('data-editor-wired');el.removeAttribute('data-image-wired');el.removeAttribute('data-section-wired');el.removeAttribute('data-card-wired')});return copy}
  function wireCards(){document.querySelectorAll(`main ${cardSelector}`).forEach(card=>{if(card.dataset.cardWired)return;card.dataset.cardWired='1';card.addEventListener('click',event=>{if(!editing)return;if(event.target.closest('a,button,summary,img'))return;selectCard(card)})});updateCardControls()}
  function addCard(){const container=selectedSection?.querySelector('.cards');if(!container){setStatus('Dieser Abschnitt hat keinen Kartenbereich');return}pushUndo();const card=document.createElement('article');card.innerHTML='<p class="eyebrow">Neue Karte</p><h3>Neue Überschrift</h3><p>Hier können Sie den Inhalt der neuen Karte bearbeiten.</p>';container.append(card);wireEditable();wireImages();wireCards();setEditable(true);selectCard(card);markDirty('Neue Karte erstellt – noch online speichern');card.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>card.querySelector('h3')?.focus(),300)}
  function duplicateCard(){if(!selectedCard)return;pushUndo();const copy=cleanClone(selectedCard);selectedCard.after(copy);wireEditable();wireImages();wireCards();selectCard(copy);markDirty('Karte dupliziert – noch online speichern');copy.scrollIntoView({behavior:'smooth',block:'center'})}
  function deleteCard(){if(!selectedCard)return;const title=(selectedCard.querySelector('h3,h2,strong')?.textContent||'diese Karte').trim();if(!confirm(`„${title}“ wirklich löschen?\n\nMit „Rückgängig“ kannst du sie wiederherstellen.`))return;pushUndo();const next=selectedCard.nextElementSibling||selectedCard.previousElementSibling;selectedCard.remove();selectedCard=null;if(next&&next.matches(cardSelector))selectCard(next);else{setContext(selectedSection?'section':'page');updateCardControls()}markDirty('Karte gelöscht – mit Rückgängig wiederherstellbar')}
  function moveCard(dir){if(!selectedCard)return;const sibling=dir<0?selectedCard.previousElementSibling:selectedCard.nextElementSibling;if(!sibling)return;pushUndo();if(dir<0)selectedCard.parentElement.insertBefore(selectedCard,sibling);else selectedCard.parentElement.insertBefore(sibling,selectedCard);markDirty('Kartenreihenfolge geändert – noch online speichern');selectedCard.scrollIntoView({behavior:'smooth',block:'nearest'});updateCardControls()}
  function cardImage(){if(!selectedCard)return;const existing=selectedCard.querySelector('img');const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=()=>{const file=input.files?.[0];if(!file)return;if(file.size>5*1024*1024){setStatus('Bild ist größer als 5 MB');return}pushUndo();const reader=new FileReader();reader.onload=()=>{let img=existing;if(!img){img=document.createElement('img');img.className=selectedCard.classList.contains('person')?'person-image':'card-image';img.alt=(selectedCard.querySelector('h3,h2')?.textContent||'Kartenbild').trim();selectedCard.prepend(img)}img.src=reader.result;img.removeAttribute('srcset');img.loading='lazy';delete img.dataset.imageWired;wireImages();markDirty(existing?'Kartenbild ersetzt – noch online speichern':'Kartenbild hinzugefügt – noch online speichern');updateCardControls()};reader.readAsDataURL(file)};input.click()}
  const originalCapture=capture;capture=()=>{if(selectedCard)selectedCard.classList.remove('card-selected');const html=originalCapture();if(selectedCard)selectedCard.classList.add('card-selected');return html.replace(/\sdata-card-wired="1"/g,'').replace(/\scard-selected/g,'')};
  const originalRestore=restore;restore=html=>{clearCard();originalRestore(html);wireCards()};
  const originalSetEditable=setEditable;setEditable=on=>{if(!on)clearCard();originalSetEditable(on);wireCards();if(on)setContext(selectedSection?'section':'page')};
  const originalSelectSection=selectSection;selectSection=section=>{if(selectedCard&&selectedCard.closest('section')!==section)clearCard();originalSelectSection(section);if(!selectedCard)setContext(section?'section':'page');updateCardControls()};
  document.querySelector('#addCard')?.addEventListener('click',addCard);document.querySelector('#cardImage')?.addEventListener('click',cardImage);document.querySelector('#cardLeft')?.addEventListener('click',()=>moveCard(-1));document.querySelector('#cardRight')?.addEventListener('click',()=>moveCard(1));document.querySelector('#duplicateCard')?.addEventListener('click',duplicateCard);document.querySelector('#deleteCard')?.addEventListener('click',deleteCard);wireCards();setContext('page');
})();
