(()=>{
'use strict';
const q=s=>document.querySelector(s),qa=s=>Array.from(document.querySelectorAll(s));let selected=null,finish=null,drag=null;
const isButton=el=>el&&el.matches('a,.btn,.ghost,button');
function checkpoint(){if(finish)finish();finish=window.__kpUndoCheckpoint?window.__kpUndoCheckpoint():null}
function done(){if(finish){finish();finish=null}}
function sheet(){let s=q('#kpDesignSheet');if(s)return s;s=document.createElement('div');s.id='kpDesignSheet';s.hidden=true;s.innerHTML=`<div class="kp-design-head"><div><small>Element bearbeiten</small><strong id="kpDesignName">Design</strong></div><button id="kpDesignClose">×</button></div><div id="kpButtonTextRow" class="kp-design-text" hidden><label>Button-Text <input id="kpButtonText" type="text"></label></div><div class="kp-design-tabs"><button data-tab="style" class="active">Design</button><button data-tab="size">Größe</button><button data-tab="space">Abstand</button></div><div class="kp-design-panel" data-panel="style"><label>Textfarbe <input id="kpColor" type="color"></label><label>Hintergrund <input id="kpBg" type="color"></label><label>Schrift <select id="kpFont"><option value="">Standard</option><option value="system-ui,-apple-system,Segoe UI,sans-serif">Modern</option><option value="Georgia,serif">Klassisch</option><option value="Arial,sans-serif">Klar</option><option value="'Trebuchet MS',sans-serif">Freundlich</option></select></label><label>Schriftgröße <input id="kpFontSize" type="range" min="10" max="96"><output id="kpFontSizeOut"></output></label><label>Rundung <input id="kpRadius" type="range" min="0" max="60"><output id="kpRadiusOut"></output></label><label>Schatten <input id="kpShadow" type="range" min="0" max="40"><output id="kpShadowOut"></output></label></div><div class="kp-design-panel" data-panel="size" hidden><label>Breite <input id="kpWidth" type="range" min="20" max="100"><output id="kpWidthOut"></output></label><label>Höhe <input id="kpHeight" type="range" min="24" max="300"><output id="kpHeightOut"></output></label><label>Innenabstand X <input id="kpPadX" type="range" min="0" max="80"><output id="kpPadXOut"></output></label><label>Innenabstand Y <input id="kpPadY" type="range" min="0" max="50"><output id="kpPadYOut"></output></label><button id="kpAutoSize">Automatische Größe</button></div><div class="kp-design-panel" data-panel="space" hidden><label>Oben/unten <input id="kpMarginY" type="range" min="0" max="80"><output id="kpMarginYOut"></output></label><label>Links/rechts <input id="kpMarginX" type="range" min="0" max="80"><output id="kpMarginXOut"></output></label></div>`;document.body.appendChild(s);
s.querySelector('#kpDesignClose').onclick=()=>{done();s.hidden=true;selected?.classList.remove('kp-design-selected')};
s.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{s.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));s.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==b.dataset.tab)});
const bind=(id,fn,event='input')=>s.querySelector(id).addEventListener(event,e=>{if(!selected)return;if(!finish)checkpoint();fn(e.target.value);outputs()});
bind('#kpButtonText',v=>selected.textContent=v);bind('#kpColor',v=>selected.style.setProperty('color',v,'important'));bind('#kpBg',v=>selected.style.setProperty('background-color',v,'important'));bind('#kpFont',v=>selected.style.setProperty('font-family',v,'important'),'change');bind('#kpFontSize',v=>selected.style.setProperty('font-size',v+'px','important'));bind('#kpRadius',v=>selected.style.setProperty('border-radius',v+'px','important'));bind('#kpShadow',v=>selected.style.setProperty('box-shadow',v>0?`0 ${Math.max(2,Math.round(v/3))}px ${v}px rgba(0,0,0,.4)`:'none','important'));bind('#kpWidth',v=>{selected.style.setProperty('width',v+'%','important');selected.style.setProperty('max-width','none','important')});bind('#kpHeight',v=>selected.style.setProperty('min-height',v+'px','important'));bind('#kpPadX',v=>{selected.style.setProperty('padding-left',v+'px','important');selected.style.setProperty('padding-right',v+'px','important')});bind('#kpPadY',v=>{selected.style.setProperty('padding-top',v+'px','important');selected.style.setProperty('padding-bottom',v+'px','important')});bind('#kpMarginY',v=>{selected.style.setProperty('margin-top',v+'px','important');selected.style.setProperty('margin-bottom',v+'px','important')});bind('#kpMarginX',v=>{selected.style.setProperty('margin-left',v+'px','important');selected.style.setProperty('margin-right',v+'px','important')});
s.querySelectorAll('input,select').forEach(x=>{x.addEventListener('change',done);x.addEventListener('pointerup',done)});s.querySelector('#kpAutoSize').onclick=()=>{checkpoint();['width','max-width','height','min-height','padding-left','padding-right','padding-top','padding-bottom'].forEach(p=>selected.style.removeProperty(p));done();load()};return s}
function hex(c){const m=(c||'').match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);return m?'#'+[m[1],m[2],m[3]].map(x=>(+x).toString(16).padStart(2,'0')).join(''):'#000000'}const px=v=>parseFloat(v)||0;
function outputs(){const s=sheet();[['kpFontSize','kpFontSizeOut',' px'],['kpRadius','kpRadiusOut',' px'],['kpShadow','kpShadowOut',''],['kpWidth','kpWidthOut',' %'],['kpHeight','kpHeightOut',' px'],['kpPadX','kpPadXOut',' px'],['kpPadY','kpPadYOut',' px'],['kpMarginY','kpMarginYOut',' px'],['kpMarginX','kpMarginXOut',' px']].forEach(([i,o,u])=>s.querySelector('#'+o).value=s.querySelector('#'+i).value+u)}
function load(){if(!selected)return;const s=sheet(),cs=getComputedStyle(selected),r=selected.getBoundingClientRect(),pr=selected.parentElement?.getBoundingClientRect();const button=isButton(selected);s.querySelector('#kpDesignName').textContent=button?'Button':selected.tagName==='IMG'?'Bild':selected.matches('section')?'Abschnitt':selected.matches('article')?'Karte':'Text';s.querySelector('#kpButtonTextRow').hidden=!button;if(button)s.querySelector('#kpButtonText').value=selected.textContent.trim();s.querySelector('#kpColor').value=hex(cs.color);s.querySelector('#kpBg').value=hex(cs.backgroundColor);s.querySelector('#kpFontSize').value=Math.max(10,Math.min(96,px(cs.fontSize)));s.querySelector('#kpRadius').value=Math.min(60,px(cs.borderRadius));s.querySelector('#kpShadow').value=cs.boxShadow==='none'?0:18;s.querySelector('#kpWidth').value=pr?.width?Math.max(20,Math.min(100,Math.round(r.width/pr.width*100))):100;s.querySelector('#kpHeight').value=Math.max(24,Math.min(300,Math.round(r.height)));s.querySelector('#kpPadX').value=Math.min(80,px(cs.paddingLeft));s.querySelector('#kpPadY').value=Math.min(50,px(cs.paddingTop));s.querySelector('#kpMarginY').value=Math.min(80,px(cs.marginTop));s.querySelector('#kpMarginX').value=Math.min(80,px(cs.marginLeft));outputs();s.hidden=false}
function select(el){selected?.classList.remove('kp-design-selected');selected=el;selected.classList.add('kp-design-selected');load()}
document.addEventListener('click',e=>{if(!document.body.classList.contains('editing')||e.target.closest('#editor,#kpDesignSheet,#kpVersionDialog'))return;const el=e.target.closest('main img,main a,main button,main h1,main h2,main h3,main p,main article,main section');if(el){e.preventDefault();e.stopPropagation();select(el)}},true);
// Buttons can be dragged like the mobile menu while editing. Position is stored as inline transform.
document.addEventListener('pointerdown',e=>{if(!document.body.classList.contains('editing'))return;const b=e.target.closest('main a.btn,main a.ghost,main button');if(!b||e.target.closest('#kpDesignSheet'))return;select(b);checkpoint();const cs=getComputedStyle(b),m=new DOMMatrixReadOnly(cs.transform==='none'?'matrix(1,0,0,1,0,0)':cs.transform);drag={b,id:e.pointerId,x:e.clientX,y:e.clientY,tx:m.m41,ty:m.m42,moved:false};b.setPointerCapture?.(e.pointerId)},true);
document.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>4)drag.moved=true;if(!drag.moved)return;e.preventDefault();drag.b.style.setProperty('transform',`translate(${drag.tx+dx}px,${drag.ty+dy}px)`,'important');drag.b.style.setProperty('position','relative','important');drag.b.style.setProperty('z-index','10','important')},{capture:true,passive:false});
document.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.id)return;if(drag.moved){e.preventDefault();done()}else done();drag=null},true);
})();
