(()=>{
'use strict';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];let selected=null;
const editing=()=>document.body.classList.contains('editing');const cp=()=>window.__kpUndoCheckpoint?.();const dirty=m=>window.markDirty?.(m)||window.dispatchEvent(new CustomEvent('kp-site-changed'));
const textSel='main h1,main h2,main h3,main h4,main h5,main h6,main p,main li,main figcaption,main blockquote,main label,main summary,.top .brand';
function makeTextEditable(){qa(textSel).forEach(el=>{if(el.closest('#editor'))return;el.contentEditable=editing()?'true':'false';el.spellcheck=true;if(el.dataset.kpUniversalText)return;el.dataset.kpUniversalText='1';let done=null;el.addEventListener('focus',()=>{if(!editing())return;done=cp();select(el)});el.addEventListener('blur',()=>{if(done){done();done=null;dirty('Text geändert – noch speichern')}})})}
function toolbar(){let b=q('#kpUniversalBar');if(b)return b;b=document.createElement('div');b.id='kpUniversalBar';b.innerHTML='<button data-bg>▧ Hintergrund</button><button data-img>▣ Bild</button><button data-text>＋ Text</button><button data-button>＋ Button</button><button data-delete>× Element</button>';document.body.append(b);b.querySelector('[data-bg]').onclick=background;b.querySelector('[data-img]').onclick=addImage;b.querySelector('[data-text]').onclick=addText;b.querySelector('[data-button]').onclick=addButton;b.querySelector('[data-delete]').onclick=remove;return b}
function select(el){selected?.classList.remove('kp-universal-selected');selected=el;if(!selected)return;selected.classList.add('kp-universal-selected');toolbar().hidden=false}
function section(){return selected?.closest('section')||q('main>section')}
function file(cb){const i=document.createElement('input');i.type='file';i.accept='image/*';i.onchange=()=>{const f=i.files?.[0];if(!f)return;if(f.size>6*1024*1024){alert('Bild ist größer als 6 MB');return}const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(f)};i.click()}
function background(){const target=selected?.closest('section')||selected?.closest('.top')||q('.top');if(!target)return;file(src=>{const done=cp();target.style.backgroundImage=`linear-gradient(#0005,#0005),url("${src}")`;target.style.backgroundSize='cover';target.style.backgroundPosition='center';target.dataset.kpBackgroundImage='1';done?.();dirty('Hintergrundbild geändert – noch speichern')})}
function addImage(){const host=section();if(!host)return;file(src=>{const done=cp(),img=document.createElement('img');img.src=src;img.alt='';img.className='kp-added-image';(host.querySelector('.wrap,.hero-copy')||host).append(img);done?.();dirty('Bild eingefügt – noch speichern');window.wireImages?.();select(img)})}
function addText(){const host=section();if(!host)return;const done=cp(),p=document.createElement('p');p.textContent='Neuer Text';(host.querySelector('.wrap,.hero-copy')||host).append(p);done?.();dirty('Textblock eingefügt – noch speichern');makeTextEditable();p.focus();select(p)}
function addButton(){const host=section();if(!host)return;const done=cp(),a=document.createElement('a');a.className='btn';a.href='#';a.textContent='Neuer Button';(host.querySelector('.wrap,.hero-copy')||host).append(a);done?.();dirty('Button eingefügt – noch speichern');select(a)}
function remove(){if(!selected||selected.matches('main,.top,section'))return;const done=cp(),next=selected.closest('section');selected.remove();selected=null;done?.();dirty('Element gelöscht – noch speichern');if(next)select(next)}
function bind(){makeTextEditable();toolbar().hidden=!editing();qa('main section,main article,main figure,main img,main a.btn,main a.ghost,.top').forEach(el=>{if(el.dataset.kpUniversal)return;el.dataset.kpUniversal='1';el.addEventListener('click',e=>{if(!editing()||e.target.closest('#kpUniversalBar,#editor'))return;select(e.target.closest(textSel+',img,a,article,figure,section,.top')||el)},true)})}
window.addEventListener('kp-editor-restored',()=>setTimeout(bind,0));new MutationObserver(bind).observe(document.body,{attributes:true,attributeFilter:['class']});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();