(()=>{
'use strict';
const endpoint='./api/editor-state.php',q=s=>document.querySelector(s),status=t=>{const el=q('#status');if(el)el.textContent=t},staticPreview=location.hostname.endsWith('github.io');
async function request(url){const r=await fetch(url,{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw Error('Server '+r.status);const type=r.headers.get('content-type')||'';if(!type.includes('application/json'))throw Error('Cloud-Funktion auf dieser Vorschau nicht verfügbar');return r.json()}
function ensureDialog(){let box=q('#kpVersionDialog');if(box)return box;box=document.createElement('div');box.id='kpVersionDialog';box.hidden=true;box.innerHTML='<div class="kp-version-backdrop"></div><section class="kp-version-sheet" role="dialog" aria-modal="true"><header><div><small>Cloud-Sicherung</small><h2>Versionen</h2></div><button type="button" class="kp-version-close">×</button></header><p class="kp-version-hint">Tippe auf einen Stand. Du kannst die Wiederherstellung danach mit Rückgängig zurücknehmen.</p><div class="kp-version-list"></div></section>';document.body.append(box);const close=()=>box.hidden=true;box.querySelector('.kp-version-close').onclick=close;box.querySelector('.kp-version-backdrop').onclick=close;return box}
function applyCompleteState(state){if(!state?.html)throw Error('Version enthält keinen Inhalt');const history=window.__kpHistory,done=window.__kpUndoCheckpoint?.();if(history&&state.editorSnapshot)history.restore(state.editorSnapshot);else{const main=q('main'),top=q('.top');if(main)main.innerHTML=state.html;if(state.header&&top)top.innerHTML=state.header;window.dispatchEvent(new CustomEvent('kp-editor-restored'))}if(state.layout?.menu&&window.kpMenuLayout)window.kpMenuLayout.apply(state.layout.menu);done?.();history?.adopt?.();document.body.classList.add('editing');const editor=q('#editor'),edit=q('#edit');if(editor)editor.hidden=false;if(edit)edit.hidden=true;window.setEditable?.(true)}
async function restoreVersion(chosen,box){try{status('Version wird geladen …');const state=await request(endpoint+'?action=version&id='+encodeURIComponent(chosen.id));applyCompleteState(state);box.hidden=true;status('Komplette Version geladen – jetzt prüfen oder mit Rückgängig zurücknehmen')}catch(err){status('Versionshistorie fehlgeschlagen: '+err.message)}}
async function openHistory(e){e?.preventDefault();e?.stopPropagation();if(staticPreview){status('Versionshistorie ist auf GitHub Pages nur Vorschau; die gespeicherten Versionen liegen auf der PHP-Testdomain.');return}status('Versionshistorie wird geladen …');try{const data=await request(endpoint+'?action=history'),versions=Array.isArray(data.versions)?data.versions:[];if(!versions.length){status('Noch keine älteren Cloud-Versionen vorhanden');return}const box=ensureDialog(),list=box.querySelector('.kp-version-list');list.innerHTML='';versions.slice(0,20).forEach((v,i)=>{const b=document.createElement('button');b.type='button';b.className='kp-version-item';const d=v.savedAt?new Date(v.savedAt):null,date=d&&!isNaN(d)?d.toLocaleDateString('de-DE'):'Gespeicherter Stand',time=d&&!isNaN(d)?d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}):'';b.innerHTML='<span class="kp-version-icon">↶</span><span class="kp-version-copy"><strong>'+date+'</strong><small>'+time+(i===0?' · Neueste Version':'')+'</small></span><span class="kp-version-arrow">›</span>';b.onclick=()=>restoreVersion(v,box);list.append(b)});box.hidden=false;status('Version auswählen')}catch(err){status('Versionshistorie fehlgeschlagen: '+err.message)}}
q('#history')?.addEventListener('click',openHistory,true);
})();